arm_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  link1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: link1_joint
    pid: {p: 10000, i: 1, d: 10}

  link2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: link2_joint
    pid: {p: 10000, i: 1, d: 10}

  link3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: link3_joint
    pid: {p: 10000, i: 1, d: 10}

  link4_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: link4_joint
    pid: {p: 10000, i: 1, d: 10}

  link5_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: link5_joint
    pid: {p: 10000, i: 1, d: 10}

  link6_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: link6_joint
    pid: {p: 10000, i: 1, d: 10}